import classNames from 'classnames';
import './page.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

const font = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PortfolioLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={classNames(
        font.className,
        'bg-[#ECE8E1] max-w-screen-xl mx-auto'
      )}
    >
      {children}
    </div>
  );
}
